ports:
        api: 4000
        websockets: 4001
        httprpc: 4002
        bzz: 4003
        p2p: 4004
datadir: "./tmp/node1"
dbpath: "./tmp/node1/iddb"
pss:
        kind: "raw"
        key: "key"
        topic: "discoverytest"
        loglevel: "critical"
discoverfreshtimeout: 10
mode: "ACTIVE"
