keystore:
        path: "./tmp/node2/keystore"
        password: "secret"
ports:
        api: 5000
        websockets: 5001
        httprpc: 5002
        bzz: 5003
        p2p: 5004
datadir: "./tmp/node2"
dbpath: "./tmp/node2/iddb"
pss:
        kind: "raw"
        key: "key"
        topic: "discoverytest"
        loglevel: "critical"
discoverfreshtimeout: 10
mode: "ACTIVE"
